"""Distribution audits derived from canonical game ledgers."""

from courtsim.analysis.artifact_archive import (
    ArtifactArchiveError,
    ArtifactArchiveResult,
    ArtifactArchiveVerification,
    ArtifactRestoreResult,
    build_artifact_archive_plan,
    create_artifact_archive,
    restore_artifact_archive,
    verify_artifact_archive,
)
from courtsim.analysis.artifact_inventory import (
    ArtifactInventoryError,
    build_artifact_inventory,
)
from courtsim.analysis.artifact_retention import (
    ArtifactRetentionError,
    build_archive_plan_from_retention_report,
    build_artifact_retention_report,
    compare_artifact_retention_reports,
)
from courtsim.analysis.audit_gates import (
    AuditComparison,
    AuditGate,
    AuditGateError,
    AuditGateReport,
    audit_comparison_to_json,
    audit_gate_report_to_json,
    audit_metric_map,
    compare_distribution_audits,
    evaluate_audit_gates,
    load_audit_gates,
    load_distribution_audit,
)
from courtsim.analysis.batch_artifacts import write_batch_audit_bundle
from courtsim.analysis.distribution import (
    DistributionAudit,
    PlayerFoulShare,
    PlayerUsageShare,
    ShareMetric,
    TeamDistributionMetrics,
    audit_game_results,
    distribution_audit_to_json,
)
from courtsim.analysis.nba_reference import (
    NbaReferenceError,
    build_nba_core_target_payload,
    build_nba_team_target_payload,
    calculate_nba_core_metrics,
    calculate_nba_team_metrics,
)
from courtsim.analysis.quick_sim_artifacts import (
    QuickSimCheckpointReceipt,
    QuickSimReferenceReceipt,
    run_quick_sim_checkpoint,
    write_observed_quick_sim_reference,
)
from courtsim.analysis.quick_sim_batch import (
    QuickSimBatchError,
    QuickSimBatchResult,
    QuickSimBatchSpec,
    quick_sim_batch_from_json,
    quick_sim_batch_to_json,
    run_quick_sim_batch,
)
from courtsim.analysis.quick_sim_comparison import (
    QuickSimComparisonError,
    QuickSimComparisonReport,
    QuickSimReference,
    QuickSimSeasonSummary,
    build_quick_sim_reference,
    compare_quick_sim_summaries,
    load_quick_sim_reference,
    quick_sim_reference_to_json,
    quick_sim_report_to_json,
    summarize_quick_sim_season,
)
from courtsim.analysis.realism_targets import (
    RealismMetricTarget,
    RealismScoreReport,
    RealismTargetError,
    RealismTargetSet,
    load_realism_target_set,
    realism_score_report_to_json,
    score_audit_against_realism_targets,
)
from courtsim.analysis.shard_merge import ShardMergeError, merge_batch_audit_shards

__all__ = [
    "ArtifactArchiveError",
    "ArtifactArchiveResult",
    "ArtifactArchiveVerification",
    "ArtifactInventoryError",
    "ArtifactRestoreResult",
    "ArtifactRetentionError",
    "AuditComparison",
    "AuditGate",
    "AuditGateError",
    "AuditGateReport",
    "DistributionAudit",
    "NbaReferenceError",
    "PlayerFoulShare",
    "PlayerUsageShare",
    "QuickSimBatchError",
    "QuickSimBatchResult",
    "QuickSimBatchSpec",
    "QuickSimCheckpointReceipt",
    "QuickSimComparisonError",
    "QuickSimComparisonReport",
    "QuickSimReference",
    "QuickSimReferenceReceipt",
    "QuickSimSeasonSummary",
    "RealismMetricTarget",
    "RealismScoreReport",
    "RealismTargetError",
    "RealismTargetSet",
    "ShardMergeError",
    "ShareMetric",
    "TeamDistributionMetrics",
    "audit_comparison_to_json",
    "audit_game_results",
    "audit_gate_report_to_json",
    "audit_metric_map",
    "build_archive_plan_from_retention_report",
    "build_artifact_archive_plan",
    "build_artifact_inventory",
    "build_artifact_retention_report",
    "build_nba_core_target_payload",
    "build_nba_team_target_payload",
    "build_quick_sim_reference",
    "calculate_nba_core_metrics",
    "calculate_nba_team_metrics",
    "compare_artifact_retention_reports",
    "compare_distribution_audits",
    "compare_quick_sim_summaries",
    "create_artifact_archive",
    "distribution_audit_to_json",
    "evaluate_audit_gates",
    "load_audit_gates",
    "load_distribution_audit",
    "load_quick_sim_reference",
    "load_realism_target_set",
    "merge_batch_audit_shards",
    "quick_sim_batch_from_json",
    "quick_sim_batch_to_json",
    "quick_sim_reference_to_json",
    "quick_sim_report_to_json",
    "realism_score_report_to_json",
    "restore_artifact_archive",
    "run_quick_sim_batch",
    "run_quick_sim_checkpoint",
    "score_audit_against_realism_targets",
    "summarize_quick_sim_season",
    "verify_artifact_archive",
    "write_batch_audit_bundle",
    "write_observed_quick_sim_reference",
]
